name: GEODACenv
channels:
  - defaults
dependencies:
  - backcall
  - blas
  - bottleneck
  - bzip2
  - cartopy
  - certifi
  - cftime
  - colorama
  - curl
  - cycler
  - decorator
  - entrypoints
  - freetype
  - geos
  - h5py
  - hdf4
  - hdf5
  - icu
  - intel-openmp
  - ipykernel
  - ipython
  - jpeg
  - jupyter_client
  - jupyter_core
  - kiwisolver
  - libcurl
  - libffi
  - libnetcdf
  - libpng
  - libssh2
  - libtiff
  - lz4-c
  - matplotlib
  - matplotlib-base
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - netcdf4
  - numexpr
  - numpy
  - numpy-base
  - openssl
  - packaging
  - pandas
  - parso
  - pickleshare
  - pillow
  - pip
  - proj
  - prompt-toolkit
  - pygments
  - pyparsing
  - pyqt
  - pyshp
  - python
  - python-dateutil
  - pytz
  - pyzmq
  - qt
  - scipy
  - setuptools
  - shapely
  - sip
  - six
  - sqlite
  - tk
  - tornado
  - traitlets
  - wcwidth
  - wheel
  - xz
  - xarray
  - zlib
  - zstd
prefix: /opt/anaconda3/envs/GEODACenv
